databases:
  - name: rl_db
    databaseName: rl
    user: rl_user

services:
  - type: web
    name: rl
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn rilakin.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rl_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
